### ISSUE TITLE
css and horizontal alignment

### ISSUE THREAD

**Issue by akissz** [Ko-fi/kofi-wordpress-button#17]
The css class btn-container, in my opinion is not functioning good along with the plugin settings for left, right, center, etc. Can you please try to improve this all so it all functions more smoothly with more types of themes? It seems to me that in most themes the alignment is forced to be centered. Or the words are left and the button is centered. The words should be stuck with the button and follow the alignment better. The 100% width seems to cause some of the problem some place.

**Comment by chris-odell-focs** [comment]
Hi what theme are you using so we can replicate what you are seeing?

**Comment by chris-odell-focs** [comment]
Tested widget and shortcut on themes TwentyTwenty, TwentyNineteen, TwentySeventeen and TwentySixteen. Alignment for all three options(left, Centre, Right) appears to be working as expected and is placed correctly within the areas of the web page.

Without further feedback wrt to the Theme and settings used in the issue created, it's not possible to verify the issue.

Therefore closing unless reported by more users.

**Comment by akissz** [comment]
Tested with right alignment and theme TwentyTwenty.
![Screen Shot 2020-09-15 at 4 23 26 PM](https://user-images.githubusercontent.com/23090286/93266644-f7db5b00-f76f-11ea-95b1-9ab7846b6eca.png)
