### ISSUE TITLE
Function error in latest update 1.2.0

### ISSUE THREAD

**Issue by robsd** [Ko-fi/kofi-wordpress-button#20]
There is a error with the latest update 1.2.0 that causes a critical error on the latest WordPress version 6.0.2.

Tested on a clean install.

Output of "debug.log" shows the following...

`[03-Oct-2022 09:15:17 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function get_plugin_data() in /home/username/public_html/wp-content/plugins/ko-fi-button/Ko_fi.php:71
Stack trace:
#0 /home/username/public_html/wp-includes/class-wp-hook.php(307): Ko_Fi::register_scripts('')
#1 /home/username/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#2 /home/username/public_html/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#3 /home/username/public_html/wp-settings.php(598): do_action('init')
#4 /home/username/public_html/wp-config.php(104): require_once('/home/username/...')
#5 /home/username/public_html/wp-load.php(50): require_once('/home/username/...')
#6 /home/username/public_html/wp-blog-header.php(13): require_once('/home/username/...')
#7 /home/username/public_html/index.php(17): require('/home/username/...')
#8 {main}
  thrown in /home/username/public_html/wp-content/plugins/ko-fi-button/Ko_fi.php on line 71`

**Comment by cameronjonesweb** [comment]
This was fixed in 1.2.1
