### ISSUE TITLE
Main Ko-fi Code Setting Overrides Widget Ko-fi Code Setting

### ISSUE THREAD

**Issue by marklchaves** [Ko-fi/kofi-wordpress-button#6]
Found this while testing my "Add to Posts" code over the holidays.

**Issue**: The widget Ko-fi **code** setting is overridden by main plugin Ko-fi **code** setting on public page, but still displays different widget code in admin page.

**Scenario**: I can go into the Ko-fi widget and add my Ko-fi code. Save it. Works great. But, if the code I added to the Ko-fi widget is different from the one I have on the main plugin settings, it has no effect. I.e., on the public facing page, my Ko-fi widget will display the **code** from the main plugin settings.

**Ideas**

1. Make Ko-fi code setting on widget read-only.
2. Allow Ko-fi code on widget to be different than Ko-fi code setting on main plugin page. But, then use the Ko-fi code from widget setting when rending the widget.

---

<img width="387" alt="ko-fi-plugin-screen-grab-2020-01-15-at-6 44 14-AM" src="https://user-images.githubusercontent.com/4658423/72389990-a0aa6400-3764-11ea-919d-d2fa6ca54e86.png" title="Widget settings">

<img width="853" alt="ko-fi-plugin-screen-grab-2020-01-15-at-6 47 49-AM" src="https://user-images.githubusercontent.com/4658423/72389987-a011cd80-3764-11ea-82a8-c38254541099.png" title="Main settings">

<img width="998" alt="ko-fi-plugin-screen-grab-2020-01-15-at-6 46 31-AM" src="https://user-images.githubusercontent.com/4658423/72389986-a011cd80-3764-11ea-8cb3-b2317e3366b6.png" title="Public facing widget">

<img width="998" alt="ko-fi-plugin-screen-grab-2020-01-15-at-6 49 21-AM" src="https://user-images.githubusercontent.com/4658423/72389988-a011cd80-3764-11ea-881b-ed31517028d4.png" title="Public facing Add to Posts">

**Comment by Jarrich** [comment]
Thanks for pointing this out. It's on our to-do list to take a look at this, currently no timeline.

**Comment by chris-odell-focs** [comment]
So proposal here is to make the code on the widget readonly and pull from the 'default code' code field on the plugin settings page. In this way the shorcode and any widget instances will all use the same code and only has to be set in one place. 

The idea being that a creator is unlikely to want to use different codes on different pages.

**Comment by chris-odell-focs** [comment]
The 'code' field on the widget is now readonly and takes it's value from the 'default code' value on the settings page.
