### ISSUE TITLE
Basic HTML share

### ISSUE THREAD

**Issue by davestewart** [Ko-fi/kofi-wordpress-button#7]
Do you guys just have a basic HTML share for a normal website?

You sharing page has everything but!

- https://help.ko-fi.com/hc/en-us/sections/360003475073-Sharing-your-Ko-fi-page

I just want some basic HTML and CSS.

Thank you :)

**Comment by Jarrich** [comment]
@davestewart The Widgets section on our website might be what you are looking for (you need to be logged in).

https://ko-fi.com/Manage/Widgets

Please let me know if that's what you are looking for.

**Comment by max23468** [comment]
> @davestewart The Widgets section on our website might be what you are looking for (you need to be logged in).
> 
> https://ko-fi.com/Manage/Widgets
> 
> Please let me know if that's what you are looking for.

In that section there's a widget working with JS, I think that @davestewart needs one which works only with HTML and CSS

**Comment by davestewart** [comment]
That's looking good, thank you!

Might be worth updating that help page because that seems to be the main thing that is linked and comes up in searches:

- https://help.ko-fi.com/hc/en-us/sections/360003475073-Sharing-your-Ko-fi-page

I'll let you know!

**Comment by davestewart** [comment]
I would love to use the JS version, but I can't in Vue, because it won't let me add script tags inside components.

Are there instructions to build it manually? Including the cute little cup-wiggle!?

(I'm a web developer by the way, so can do whatever is needed)

**Comment by max23468** [comment]
I don't think it's possible to build an animated button with only HTML and CSS (with no JS), but maybe Ko-fi team knows any alternative solution

**Comment by davestewart** [comment]
Ah sorry - you miss my point.

I just need to assemble the HTML, JS and CSS manually.

I can use scripts, just not the script tag.

I suppose I could just copy the script into my component...

**Comment by Jarrich** [comment]
@max23468 The wiggle animation is pure CSS. The widget itself is fairly basic and if you need a quick solution I'd suggest trying to incorporate the button manually into your solution. I will raise this internally and explore a maintainable solution that's more elegant.

**Comment by davestewart** [comment]
Just looking at the script now.

It would be nice to have an option that didn't use `document.writeln` but just returned the HTML so it could be used in web apps.

EDIT: Oh - there is!

I'll just butcher the script and my end and will have it in the site in a jiffy!

**Comment by max23468** [comment]
Thank you!

BTW I've found that using the widget gives this error to Chrome DevTools
`A cookie associated with a cross-site resource at https://ko-fi.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.`

**Comment by max23468** [comment]
Other warning I get when I post the widget in my WordPress site via HTML widget is:

Uncaught ReferenceError: kofiwidget2 is not defined
    at data:text/javascript;base64, a29maXdpZGdldDIuaW5pdCgnU3VwcG9ydGEgVGVtaXMgdmlhIEtvLWZpJywnIzI5YWJlMCcsJ1E1UTUxR1NITycpO2tvZml3aWRnZXQyLmRyYXcoKTs=:1

(anonymous) | @ | data:text/javascript…nZXQyLmRyYXcoKTs=:1
-- | -- | --

**Comment by davestewart** [comment]
OK, a Vue implementation is as simple as adding this:

Page:

```html
<script type='text/javascript' src='https://ko-fi.com/widgets/widget_2.js'></script>
```

Component:

```vue
<template>
  <div class="kofi" v-html="html"></div>
</template>

<script>
const colors = {
  blue: '#019cde',
  grey: '#4b798d',
  red: '#ff5f5f',
  green: '#46b798',
  black: '#323b43',
}

export default {
  computed: {
    html () {
      return kofiwidget2.getHTML()
    }
  },

  created () {
    const text = 'Buy me a coffee :)'
    const page = 'gotpaper'
    const color = colors.red
    kofiwidget2.init(text, color, page);
  }
}
</script>


<style lang="scss" scoped>
.kofi {
  // your styles here
}
```

Thanks all!

**Comment by Jarrich** [comment]
Thank you @davestewart
